server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:file:./data/hero-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.hibernate.SQL: DEBUG
